site_name: ai-lab docs
theme:
  name: material
docs_dir: docs
nav:
  - Home: index.md
  - Roadmap: ROADMAP.md
  - Checklists: checklists.md
  - Links: links.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
