site_name: ai-lab docs
theme:
  name: material
docs_dir: docs
nav:
  - Home: index.md
  - Roadmap: ROADMAP.md
  - Plan:
    - Master Plan: PLAN.md
    - 8-Week: 8-week-plan.md
    - Foundations: foundations.md
    - KPIs: kpis.md
    - Checklists:
      - RAG Eval: checklists/rag_eval.md
      - Recsys Eval: checklists/recsys_eval.md
    - Sprints:
      - Week 1: sprints/week-01.md
      - Week 2: sprints/week-02.md
      - Week 3: sprints/week-03.md
      - Week 4: sprints/week-04.md
      - Week 5: sprints/week-05.md
      - Week 6: sprints/week-06.md
      - Week 7: sprints/week-07.md
      - Week 8: sprints/week-08.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
