name: monthly-longform-issue
on:
  schedule:
    - cron: '30 5 * * 0'   # Sundays 05:30 UTC == 11:00 IST
  workflow_dispatch:
jobs:
  open_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create Monthly Longform Issue (first Sunday IST only)
        uses: actions/github-script@v7
        with:
          script: |
            const now = new Date();
            const ist = new Date(now.getTime() + (5.5 * 60 * 60 * 1000));
            const day = ist.getUTCDay();
            const date = ist.getUTCDate();
            if (day !== 0 || date > 7) { return; }
            const y = ist.getUTCFullYear();
            const m = String(ist.getUTCMonth()+1).padStart(2,'0');
            const title = `Monthly Longform: ${y}-${m}`;
            const body = `Write 1,000–1,500 words. Include: problem, design, metrics, code snippet, lessons. Add link to docs/links.md.`;
            const { data: issues } = await github.rest.search.issuesAndPullRequests({ q: `repo:${context.repo.owner}/${context.repo.repo} is:issue is:open in:title \"${title}\"` });
            if (issues.total_count === 0) {
              await github.rest.issues.create({ owner: context.repo.owner, repo: context.repo.repo, title, body, labels: ['longform','docs'] });
            }
